sonar.projectKey=AparnaMounikau763_sample-ci-cd-app
sonar.projectName=Flask CI CD App

sonar.organization=aparnamounikau763

# ✅ safest approach: define root explicitly
sonar.sources=.
sonar.tests=tests

# ✅ prevent test duplication
sonar.test.inclusions=tests/**

# ✅ exclude tests from main analysis
sonar.exclusions=**/__pycache__/**,tests/**

sonar.python.version=3.10
sonar.sourceEncoding=UTF-8