sonar.projectKey=AparnaMounikau763_sample-ci-cd-app
sonar.projectName=Flask CI CD App

sonar.organization=aparnamounikau763

sonar.sources=.
sonar.tests=tests

sonar.python.version=3.10
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**