apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
      - name: jfrog-secret
      tolerations:   # 👈 ADD THIS BLOCK
      - operator: "Exists"
      containers:
      - name: flask-app
        image: aparnamounika7.jfrog.io/fjpd-docker-local/flask-app:latest
        ports:
        - containerPort: 5000