name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # ✅ FIX IS HERE
    - name: Run Tests
      run: |
        PYTHONPATH=. pytest -v

  docker-build-push:
    needs: build-test-scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
<<<<<<< HEAD
      run: docker build -t flask-app:latest .
=======
      run: docker build -t flask-app:latest .
>>>>>>> 3b8c8829d61e71acfc94551c8358c25b0e09d35d
