name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: flask-app
  JFROG_REGISTRY: aparnamounika7.jfrog.io
  JFROG_REPO: fjpd-docker-local

jobs:

# =========================
# 1. BUILD + TEST + SONAR
# =========================
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.20"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run Tests with Coverage
      run: |
        PYTHONPATH=. pytest --cov=. --cov-report=xml

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey=flask-ci-cd-app
          -Dsonar.python.coverage.reportPaths=coverage.xml

# =========================
# 2. DOCKER BUILD + PUSH TO JFROG
# =========================
  docker-build-push:
    needs: build-test-scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Login to JFrog
    - name: Login to JFrog Artifactory
      run: |
        echo "${{ secrets.JFROG_PASSWORD }}" | docker login $JFROG_REGISTRY \
        -u ${{ secrets.JFROG_USERNAME }} --password-stdin

    # Build Image
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    # Tag Image (FIXED FORMAT)
    - name: Tag Docker Image
      run: |
        docker tag $IMAGE_NAME:latest \
        $JFROG_REGISTRY/$JFROG_REPO/$IMAGE_NAME:${{ github.run_number }}

    # Push Image (ONLY ONCE)
    - name: Push Docker Image to JFrog
      run: |
        docker push $JFROG_REGISTRY/$JFROG_REPO/$IMAGE_NAME:${{ github.run_number }}

# =========================
# 3. DEPLOY TO EKS
# =========================
  deploy-to-eks:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region : $ {{ secrets.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --name ${{ secrets.EKS_CLUSTER_NAME }} \
          --region $ {{ secrets.AWS_REGION }}  

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/flask-app \
        flask-app=$JFROG_REGISTRY/$JFROG_REPO/$IMAGE_NAME:${{ github.run_number }}

        kubectl rollout status deployment/flask-app
